services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - event

  auth:
    build: ./auth
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  event:
    build: ./event
    ports:
      - "3002:3002"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: